name: LastHolo
version: 4.0.0.7
description: Chat with holograms if has permission!
main: com.gmail.JyckoSianjaya.LastHolo.LastHolo
author: Jycko Sianjaya
softdepend: [WorldGuard,WorldEdit,CommandPrompter]
commands:
     lastholo:
            usage: /<command>
            aliases: [lasth,lh,lholo,holochat]
            description: The last Holo commands!